name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # ✅ REQUIRED
          java-version: '17'

      - name: Compile
        run: javac Main.java

      - name: Run
        run: java Main
